
package src.main.java.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AcademicWebServicesService", targetNamespace = "http://servicios/", wsdlLocation = "http://localhost:7777/ws/AcademicWebServices?wsdl")
public class AcademicWebServicesService
    extends Service
{

    private final static URL ACADEMICWEBSERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACADEMICWEBSERVICESSERVICE_EXCEPTION;
    private final static QName ACADEMICWEBSERVICESSERVICE_QNAME = new QName("http://servicios/", "AcademicWebServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/ws/AcademicWebServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACADEMICWEBSERVICESSERVICE_WSDL_LOCATION = url;
        ACADEMICWEBSERVICESSERVICE_EXCEPTION = e;
    }

    public AcademicWebServicesService() {
        super(__getWsdlLocation(), ACADEMICWEBSERVICESSERVICE_QNAME);
    }

    public AcademicWebServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACADEMICWEBSERVICESSERVICE_QNAME, features);
    }

    public AcademicWebServicesService(URL wsdlLocation) {
        super(wsdlLocation, ACADEMICWEBSERVICESSERVICE_QNAME);
    }

    public AcademicWebServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACADEMICWEBSERVICESSERVICE_QNAME, features);
    }

    public AcademicWebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcademicWebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AcademicWebServices
     */
    @WebEndpoint(name = "AcademicWebServicesPort")
    public AcademicWebServices getAcademicWebServicesPort() {
        return super.getPort(new QName("http://servicios/", "AcademicWebServicesPort"), AcademicWebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcademicWebServices
     */
    @WebEndpoint(name = "AcademicWebServicesPort")
    public AcademicWebServices getAcademicWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios/", "AcademicWebServicesPort"), AcademicWebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACADEMICWEBSERVICESSERVICE_EXCEPTION!= null) {
            throw ACADEMICWEBSERVICESSERVICE_EXCEPTION;
        }
        return ACADEMICWEBSERVICESSERVICE_WSDL_LOCATION;
    }

}
